*Задание 1*

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [29]:
N = int(input("Введите размер array: "))

li = []

for i in range(0,N+1):
    li = [i] + li

x = np.array(li)
x

Введите размер array: 15


array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

*Задание 2*

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [32]:
y = x.reshape(4,4)
y

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [33]:
total_sum = 0

for i in range(len(y[0])):
    total_sum += y[i][i]

total_sum

30

*Задание 3*

Решите систему уравнений:
4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [14]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])
b = np.array( [4, 12, -3] )

from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [15]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [25]:
print(round(4*0.46666667+2*3.84444444+(-5.55555556)))
print(round(0.46666667+3*3.84444444))
print(round(5*3.84444444+4*(-5.55555556)))

4
12
-3
